In [112]:
print("hello")

hello


In [113]:
a,b=1,4
a+b

5

In [114]:
def isPaire(a):
    if a%2==0:
        return True, "is pair"
    return False,"is impair"

In [115]:
isPaire(5), isPaire(6)

((False, 'is impair'), (True, 'is pair'))

In [116]:
a,b=isPaire(5)
a

False

In [117]:
L=[1,2]
L.append(5)
L
L.remove(1)
L

[2, 5]

In [118]:
L1=[4,5]
L2=L+L1
L2

[2, 5, 4, 5]

In [119]:
len(L2)

4

In [120]:
L

[2, 5]

In [121]:
L1

[4, 5]

In [122]:
L3=[]
for i,j in zip(L,L1):
    L3.append(i+j)
L3

[6, 10]

In [123]:
L=[[1,2,3],[5,6,7]]
len(L)

2

In [124]:
len(L[0])

3

In [125]:
import numpy as np
a=np.array([1,2])
a

array([1, 2])

In [126]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [127]:
c=np.ones(5,dtype=int) # np.zeros(5,dtype=int)
c

array([1, 1, 1, 1, 1])

In [128]:
d=np.arange(1,2,0.1)
d

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [129]:
len(d)

10

In [130]:
d.size

10

In [131]:
e=np.linspace(4,2,5)
e

array([4. , 3.5, 3. , 2.5, 2. ])

In [132]:
x=np.array([1,2,3])
y=np.array([5,6,7])
z=x+y
z

array([ 6,  8, 10])

In [133]:
m1=np.array([[1,2],[3,4],[2,1]])
m2=np.array([[2,2],[4,4],[3,1]])
m3=m1+m2
m3

array([[3, 4],
       [7, 8],
       [5, 2]])

In [134]:
m3.ndim

2

In [135]:
m3.shape

(3, 2)

In [136]:
m3.size

6

In [139]:
x=m2.reshape(2,3)
x

array([[2, 2, 4],
       [4, 3, 1]])

In [149]:
M1=np.array([[1,2],[3,4]])
value=M1[1,1]
lin=M1[0,:]
col=M1[:,1]
print(value)
print(lin)
print(col)

4
[1 2]
[2 4]


In [174]:
T=np.array([4,6,8])
np.shape(T)[0]
somme=0
for i in T:
    somme=somme+(i-np.mean(T))**2
somme/len(T)

2.6666666666666665

In [186]:
np.sqrt(np.sum((T-np.mean(T))**2)/len(T))

1.632993161855452

In [187]:
std=np.std(T)
std

1.632993161855452